#!/bin/sh /etc/rc.common
# Copyright (c) 2011-2015 OpenWrt.org

START=21

add_static_ip() {

	uci -q batch <<-EOF >/dev/null
		add dhcp host
		set dhcp.@host[-1].name=K2P_1
		set dhcp.@host[-1].dns=1
		set dhcp.@host[-1].mac=68:DB:54:E7:BD:80
		set dhcp.@host[-1].ip=${1}.${2}.${3}.20
		set dhcp.@host[-1].leasetime=infinite
		
		add dhcp host
		set dhcp.@host[-1].name=K2P_2
		set dhcp.@host[-1].dns=1
		set dhcp.@host[-1].mac=74:7D:24:93:9A:10
		set dhcp.@host[-1].ip=${1}.${2}.${3}.21
		set dhcp.@host[-1].leasetime=infinite
		
		add dhcp host
		set dhcp.@host[-1].name=TL-SG2008D
		set dhcp.@host[-1].dns=1
		set dhcp.@host[-1].mac=3C:6A:48:2E:FA:35
		set dhcp.@host[-1].ip=${1}.${2}.${3}.30
		set dhcp.@host[-1].leasetime=infinite
		
		add dhcp host
		set dhcp.@host[-1].name=Panther_X2
		set dhcp.@host[-1].dns=1
		set dhcp.@host[-1].mac=D6:90:C6:2C:A4:D4
		set dhcp.@host[-1].ip=${1}.${2}.${3}.50
		set dhcp.@host[-1].leasetime=infinite
		
		commit dhcp
	EOF

	/etc/init.d/dnsmasq restart
	return 0
}

set_sideroute_ip() {

	uci -q batch <<-EOF >/dev/null
		set network.lan.gateway=${1}.${2}.${3}.1
		set network.lan.dns=${1}.${2}.${3}.1
		
		commit network
	EOF

	/etc/init.d/network restart
	return 0
}

set_default_theme() {

	uci -q batch <<-EOF >/dev/null
		set luci.main.mediaurlbase=/luci-static/argone
		
		commit luci
	EOF

	return 0
}


start() {

	local static_host_name=$(uci -q get dhcp.@host[$index].name)
	
	local op_lan_ipaddr=$(uci get network.lan.ipaddr)
	local op_lan_ipaddr_1st=$(uci get network.lan.ipaddr | awk -F '.' '{print $1}')
	local op_lan_ipaddr_2nd=$(uci get network.lan.ipaddr | awk -F '.' '{print $2}')
	local op_lan_ipaddr_3rd=$(uci get network.lan.ipaddr | awk -F '.' '{print $3}')
	local op_lan_ipaddr_4th=$(uci get network.lan.ipaddr | awk -F '.' '{print $4}')
	
	local op_lan_gateway=$(uci get network.lan.gateway)
	local op_lan_gateway_4th=$(uci get network.lan.gateway | awk -F '.' '{print $4}')
	
	if [ "$op_lan_ipaddr_4th" == "1" ]; then
	
		if [ "$static_host_name" == "K2P_1" ]; then
		
			echo "The static_ip has already exit"
			
		else
		
			add_static_ip $op_lan_ipaddr_1st $op_lan_ipaddr_2nd $op_lan_ipaddr_3rd
			
			set_default_theme
			
			echo "The static_ip has added success"
		
		fi
		
	else
	
		echo "The device is sideroute"
	
		if [ "$op_lan_gateway_4th" == "1" ]; then
		
			echo "This sideroute has already setted"
			
		else
		
			set_sideroute_ip $op_lan_ipaddr_1st $op_lan_ipaddr_2nd $op_lan_ipaddr_3rd
			
			set_default_theme
			
			echo "The sideroute_ip has setted success"
		
		fi
		
	fi
	
	exit 0
}

stop() {
    echo stop
}
