#!/bin/sh
#============================================================
# File name: update-adguard-core
# Description: update adguard core
# Author: Gabrielxzx
# https://github.com/Gabrielxzx
#============================================================


source "/etc/openwrt_release"
case "${DISTRIB_ARCH}" in
	aarch64_*)
		CORE_ARCH="arm64"
		;;
	arm_*_neon-vfp*)
		CORE_ARCH="armv7"
		;;
	arm_*_neon|arm_*_vfp*)
		CORE_ARCH="armv6"
		;;
	arm*)
		CORE_ARCH="armv5"
		;;
	i386_*)
		CORE_ARCH="386"
		;;
	mips64_*)
		CORE_ARCH="mips64"
		;;
	mips_*)
		CORE_ARCH="mips-softfloat"
		;;
	mipsel_*)
		CORE_ARCH="mipsle-softfloat"
		;;
	x86_64)
		CORE_ARCH="amd64"
		;;
	*)
		CORE_ARCH="0"
		;;
esac

AdGuardHome_state=$(grep "option enabled" /etc/config/AdGuardHome | awk -F ' ' '{print $3}')

echo 设备结构为linux-$CORE_ARCH

AGH_CORE=$(curl -sL https://api.github.com/repos/AdguardTeam/AdGuardHome/releases/latest | grep /AdGuardHome_linux_$CORE_ARCH | awk -F '"' '{print $4}')

wget -q $AGH_CORE

tar -zxvf AdGuardHome_linux_$CORE_ARCH.tar.gz

/etc/init.d/AdGuardHome stop

mv AdGuardHome/AdGuardHome /usr/bin

chmod +x /usr/bin/AdGuardHome

rm -rf /root/AdGuardHome_linux_$CORE_ARCH.tar.gz
rm -rf /root/AdGuardHome

if [ "$AdGuardHome_state" == "'1'" ]; then

    /etc/init.d/AdGuardHome start

else

	/etc/init.d/AdGuardHome stop

fi

echo adguardhome core update success